{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "helm_chart_k8s.labels" . | nindent 4 }}
    role: api
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    role: api
{{- end }}
