{{- if .Values.frontend.enabled }}
# Frontend Service - Exposes frontend internally on port 3000
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "helm_chart_k8s.labels" . | nindent 4 }}
    role: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    role: frontend
{{- end }}
